### ISSUE TITLE
Issue with source code

### ISSUE THREAD

**Issue by VityaSchel** [templatio/admin#1]
So I digged up the source code of this project and GOD WHAT I FOUND!!!!
THIS IS THE VUE! 😡😡😡😡 NOT REACT???? 😨🤯😳 FUCK ME! VUE SUCKS 😭🥵 WHY? ❓🅰️🅱️🅾️🅱️🅰️ WHY VUE SUCKS? 👎🏿👎🏻👎🏿👎🏿
BECAUSE ITS NOT REACTJS 👁👄👁😬 FUCK VUE AND ITS DEVELOPERS 🤡🤡🤡🤡🤡🤡🤡

**Comment by martiliones** [comment]
ok retard.

**Comment by VityaSchel** [comment]
FUCKING VUE DEVELOPER 🤢🤮👹 TELLS ME TO SHUT UP 😵🤐🙄 DISLIKES ME 👎🏼 😢 FOR TELLING THE TRUTH 😤😱👨‍🎤
